# clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-k8s-admin
subjects:
- kind: ServiceAccount
  name: sa-k8s
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin  # This is a default ClusterRole that gives full access
  apiGroup: rbac.authorization.k8s.io