apiVersion: v1
kind: Service
metadata:
  name: biotune-ai
spec:
  type: ClusterIP # we don't need LoadBalancer since ngrok now handles this for us
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: biotune-ai   # Matches your pod labels
